### ISSUE TITLE
load if in background?

### ISSUE THREAD

**Issue by kintaro1981** [cazala/react-coin-hive#2]
react-coin-hive will activate the miner in case a browser tab is in the background?

**Comment by cazala** [comment]
To be honest, I don't know. This uses [react-idle](https://github.com/ReactTraining/react-idle) to notify when the user is inactive. You could try asking on [their repo](https://github.com/ReactTraining/react-idle).

**Comment by katopz** [comment]
So there is no way to click to start?

**Comment by cazala** [comment]
No, this uses `react-idle` to start/stop the miner
