### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by g33kidd** [cazala/react-coin-hive#3]
Was just thinking about this and wondering if it would work with React Native?

**Comment by cazala** [comment]
No, this component would not work with react native

**Comment by lelvisl** [comment]
why?

**Comment by cazala** [comment]
Well, I have never used react native but I don't think this would work, I'm manipulating the DOM directly via vanilla javascript.. it doesn't sound like something you can do in react native since there no DOM at all in a native app..
